# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2cf50aa9517d6fdc1814621ef349d584271af24db523611f538c98c98ab114a1fc7ee625452a9a174b674f5ac71b3c122604724e80fd28a699a2246097c1757

test:
  secret_key_base: 0651b2415de9e3f859b0dd7faeb27686035c4687bd52770ef1038bfef356b55b139f3a191ec82b3c70a7e142cbf6ed6339cbe0d06bc95e0da8d3efa9fd2d7322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
